### ISSUE TITLE
Add method to retrieve crates based on category

### ISSUE THREAD

**Issue by mainrs** [theduke/crates-io-api#24]
Maybe this is already possible with the current query api but I couldn't really figure it out. My goal is to get a list of the top 100 crates of each category.

Skimming through the code this doesn't seem to be supported currently.

**Comment by theduke** [comment]
This crate can only support things the `crates.io` pseudo-api offers.

That's generally only what you can see on https://crates.io.

I don't think there is a listing of the top crates per category.

**Comment by SirWindfield** [comment]
Apparently https://crates.io/categories/command-line-utilities (a category page) does do a network request to:
```https://crates.io/api/v1/crates?category=command-line-utilities&page=1&per_page=10&sort=recent-downloads```

The current API doesn't provide a way to actually access the above URL. There is currently no way to specify the `category` parameter.

**Comment by theduke** [comment]
Ah, good to know. 

Happy to accept a PR.
