### ISSUE TITLE
Deprecate Authors::users field

### ISSUE THREAD

**Issue by Nemo157** [theduke/crates-io-api#25]
From [the crates.io source](https://github.com/rust-lang/crates.io/blob/1fff9e99796b7e3c3be49f69f7ad688d2749a09e/src/controllers/version/metadata.rs#L46-L48):

> It was imagined that we wold associate authors with users. This was never implemented. This complicated return struct is all that is left, hear for backwards compatibility.

To reduce confusion it would be good to deprecate the `users` field on `Authors` since it is never planned to be anything other than an empty list.

**Comment by theduke** [comment]
Will be removed in the next release.
