### ISSUE TITLE
Add user_id to ListOptions

### ISSUE THREAD

**Issue by orhanbalci** [theduke/crates-io-api#37]
In order to list a user's crates client should be able to pass user_id parameter to 
[crates](https://docs.rs/crates_io_api/latest/crates_io_api/struct.SyncClient.html#method.crates) endpoint. user_id parameter can be obtained from [this](https://github.com/theduke/crates_io_api/issues/36) endpoint. 

Example query: https://crates.io/api/v1/crates?page=1&per_page=10&sort=alpha&user_id=18551

**Comment by theduke** [comment]
Closed by #40
