### ISSUE TITLE
License is None 

### ISSUE THREAD

**Issue by alenpaul2001** [theduke/crates-io-api#50]
The [License](https://docs.rs/crates_io_api/latest/crates_io_api/struct.Crate.html#structfield.license) field of the struct [Crate](https://docs.rs/crates_io_api/latest/crates_io_api/struct.Crate.html) is always None

```rust
async fn asyncmain() {
    let client: AsyncClient = AsyncClient::new(
        "something (no@email.com)",
        std::time::Duration::from_millis(1500),
    )
    .unwrap();
    let mut cquery = CratesQuery::builder()
        .search("rand")
        .page_size(1)
        .sort(Sort::Relevance)
        .build();
    cquery.set_page(1);
    let result = client.crates(cquery).await.unwrap();
    println!("{:?}", result.crates[0].license);
}
```

output
`None`

expected output
`MIT OR Apache-2.0`

**Comment by theduke** [comment]
The API doesn't return the license on list queries, only when retrieving a crate directly.

The `Crate::license` field is actually always empty. I believe this might be a relic of previous API responses.

To get the license, you have to retrieve the crate via `Client::get_crate` and then inspect the `Version::license` field.
