### ISSUE TITLE
Add `recent_downloads` for `FullCrate`

### ISSUE THREAD

**Issue by ginger51011** [theduke/crates-io-api#62]
Right now, only `Crate` contains `recent_downloads`. However, the name of `FullCrate` seem to indicate to me that it should contain a superset of the fields of `Crate`. Am I missing some way of accessing this field?

Is this due to the underlying API, or would it be easy to add this field to `FullCrate`?

**Comment by theduke** [comment]
Probably just an oversight.

You can easily check what the API returns by opening the devtools when browsing crates.io.

Happy to receive a PR that adds the field.
